sed -i '56a\
import { GLOBAL_CASHEW_COMPANIES, GLOBAL_CASHEW_BUYER_PROFILES, GLOBAL_CASHEW_PRODUCTS, GLOBAL_CASHEW_RFQS } from "./cashewData";\
import { GLOBAL_VANILLA_COMPANIES, GLOBAL_VANILLA_BUYER_PROFILES, GLOBAL_VANILLA_PRODUCTS, GLOBAL_VANILLA_RFQS } from "./vanillaBeansData";' src/data/mockData.ts
