const fs = require('fs');

const rawListings = [
  {
    type: 'Supplier',
    name: 'UKKL Company Limited',
    products: 'sunflower oil, soybeans oil, edible oils, health supplements, cosmetics',
    established: 2007,
    employees: '1-5',
    desc: 'Engaged in the business of selling consumer products such as, edible oils, health supplements and cosmetics.',
    location: 'United States - Wyoming',
    contactPerson: 'Samrit Thanakhun',
    phone: '+1-315-961',
    email: '—'
  },
  {
    type: 'Supplier',
    name: 'Stacey Chem Sales',
    products: 'Agro chemicals, urea fertilizer, ammonium, soybeans, yellow corn, copper wire scrap, wheat flour',
    established: 2008,
    employees: '101-500',
    desc: 'We use a reliable shipping company and achieve 100% success in all countries. Agro chemicals, urea fertilizer, ammonium, soybeans, yellow corn, copper wire scrap, wheat flour.',
    location: 'United States - Nevada',
    contactPerson: 'Andy Henderson',
    phone: '+660324003240003',
    email: '—'
  },
  {
    type: 'Supplier',
    name: 'GTC Global Trade Company',
    products: 'Soybeans, Sun Flower Seeds, Castor Seeds, Maize, Kidney Beans',
    established: 2021,
    employees: '1-5',
    desc: 'Supplier of Soybeans, Sun Flower Seeds, Castor Seeds, Maize, Kidney Beans.',
    location: 'United States - Washington',
    contactPerson: 'Noah Tess',
    phone: '+17789198251924613731',
    email: '—'
  },
  {
    type: 'Manufacturer',
    name: 'Agc Export S.A',
    products: 'Corn Oil, Soybean Oil, Peanut Oil, Rapeseed Oil, Sunflower Oil, Coconut Oil, Cooking Oil, Vegetable Oil, Edible Oil, Oils',
    established: 1990,
    employees: 'Above 1000',
    desc: 'Manufacturer of Corn Oil, Soybean Oil, Peanut Oil, Rapeseed Oil, Sunflower Oil, Coconut Oil, Cooking Oil, Vegetable Oil, Edible Oil, Oils.',
    location: 'United States - California',
    contactPerson: 'Erick Rodriguez',
    phone: '+1-563-307',
    email: '—'
  },
  {
    type: 'Supplier',
    name: 'KHM New-Energy ITL',
    products: 'METHYL OLEATE, EPOXIDIZED SOYBEAN OIL, ETHYL OLEATE, METHYL PALMITATE',
    established: 2018,
    employees: '6-10',
    desc: 'Supplier of METHYL OLEATE, EPOXIDIZED SOYBEAN OIL, ETHYL OLEATE, METHYL PALMITATE.',
    location: 'United States - Texas',
    contactPerson: 'Patric wilsons',
    phone: '+1-210-4818603',
    email: '—'
  },
  {
    type: 'Buyer',
    name: 'Kingdom Investment Resources, LLC',
    products: 'soybean, sugar, scrap, crude oil, diamonds',
    established: 2008,
    employees: '1-5',
    desc: 'I have buyer seeking real suppliers for crude oil, diamonds, sugar, soybeans, and more.',
    location: 'United States - GA',
    contactPerson: 'Valerie Barner',
    phone: '+14703579417-357-9417',
    email: '—'
  },
  {
    type: 'Supplier',
    name: 'Multi-Source B.V',
    products: 'Soybean Oil, Non gmo soybean, Sugar, Chicken feet',
    established: 2006,
    employees: '11-50',
    desc: 'Supplier of Soybean Oil, Non gmo soybean, Sugar, Chicken feet.',
    location: 'United States - Texas',
    contactPerson: 'Paul Noar',
    phone: '+1-306-7810452',
    email: 'gulfers448@gmail.com'
  },
  {
    type: 'Supplier',
    name: 'Angel CR Inc',
    products: 'Cooking oil, sunflower oil, wholesale sunflower oil sales, wholesale cooking oil, soybean oil, wholesale soybean oil',
    established: 2018,
    employees: '6-10',
    desc: 'Supplier of Cooking oil, sunflower oil, wholesale sunflower oil sales, wholesale cooking oil, soybean oil, wholesale soybean oil.',
    location: 'United States - New York',
    contactPerson: 'Ramal Huseynov',
    phone: '+1-718-6039098',
    email: '—'
  },
  {
    type: 'Supplier',
    name: 'RW-Vermall.Inc',
    products: 'Animal feed, Corn, Milk, Soybean Oil',
    established: 2018,
    employees: '11-50',
    desc: 'Supplier of Animal feed, Corn, Milk, Soybean Oil.',
    location: 'United States - Texas',
    contactPerson: 'Rami Wilsons',
    phone: '+1-321-5710832',
    email: '—'
  },
  {
    type: 'Supplier',
    name: 'Hanifi and Associates',
    products: 'Halal Beef, Halal Chicken, Sugar, Soybeans, Rice, Halal Lamb, Crude Oil, Wheat',
    established: 2016,
    employees: '1-5',
    desc: 'Supplier of Halal Beef, Halal Chicken, Sugar, Soybeans, Rice, Halal Lamb, Crude Oil, Wheat.',
    location: 'United States - Michigan',
    contactPerson: 'Shahied Hanifa',
    phone: '+1-248-4441460',
    email: '—'
  },
  {
    type: 'Manufacturer',
    name: 'Jedwards International Inc',
    products: 'sunflower oil, corn oil, jatropha oil, soybean oil, used cooking oil, rapeseed oil, RBD Palm Olein',
    established: 2017,
    employees: '11-50',
    desc: 'Manufacturer of sunflower oil, corn oil, jatropha oil, soybean oil, used cooking oil, rapeseed oil, RBD Palm Olein.',
    location: 'United States - Texas',
    contactPerson: 'mike john',
    phone: '+1-617-4729300',
    email: '—'
  },
  {
    type: 'Supplier',
    name: 'Awad & Griffith Global Trade LLC',
    products: 'Soybeans, Corn Maize, Wheat',
    established: 2020,
    employees: '1-5',
    desc: 'Supplier of Soybeans, Corn Maize, Wheat.',
    location: 'United States - New York',
    contactPerson: 'Bala Awad',
    phone: '+1-203-6004362',
    email: '—'
  },
  {
    type: 'Supplier',
    name: 'Stephens International',
    products: 'Soybeans, steel, Cigarettes, I.V supplies',
    established: 2005,
    employees: '6-10',
    desc: 'Supplier of Soybeans, steel, Cigarettes, I.V supplies.',
    location: 'United States - Georgia',
    contactPerson: 'Chinel Stephens',
    phone: '+914-327-8123',
    email: '—'
  },
  {
    type: 'Supplier',
    name: '1Arena',
    products: 'rice, corn, soybean',
    established: 1989,
    employees: '101-500',
    desc: 'Supplier of rice, corn, soybean.',
    location: 'United States - Minnesota',
    contactPerson: 'One Arena',
    phone: '+1-612-4545899',
    email: '—'
  },
  {
    type: 'Supplier',
    name: 'AJ Global, LLC',
    products: 'TVP, TSP, grain, seafood, hake, sesame, tomato paste, soybean meal, powder milk',
    established: 2009,
    employees: '11-50',
    desc: 'Supplier of TVP, TSP, grain, seafood, hake, sesame, tomato paste, soybean meal, powder milk.',
    location: 'United States - TX',
    contactPerson: 'Tony Kwon',
    phone: '+1-956-3601460',
    email: '—'
  },
  {
    type: 'Supplier',
    name: 'Jeron Group',
    products: 'coal, coking coal, pet coke, wheat, corn, soybeans, sugar',
    established: 2015,
    employees: '1-5',
    desc: 'Supplier of coal, coking coal, pet coke, wheat, corn, soybeans, sugar.',
    location: 'United States - North Carolina',
    contactPerson: 'Jeff Davis',
    phone: '+1-704-9462467',
    email: '—'
  },
  {
    type: 'Supplier',
    name: 'Capital Funds International Inc.',
    products: 'crude oil, SOYBEAN OIL, SUNFLOWER OIL, BITUMEN',
    established: 2010,
    employees: '11-50',
    desc: 'Supplier of crude oil, SOYBEAN OIL, SUNFLOWER OIL, BITUMEN.',
    location: 'United States - Illinois',
    contactPerson: 'Adan Akishemohin',
    phone: '+1-607-4421419',
    email: '—'
  },
  {
    type: 'Supplier',
    name: 'TradeBreeze Logitics',
    products: 'corn, yellow corn, maize, yellow maize, grain, animal feed, Soybeans, Hard Red Winter Wheat',
    established: 2022,
    employees: '1-5',
    desc: 'Supplier of corn, yellow corn, maize, yellow maize, grain, animal feed, Soybeans, Hard Red Winter Wheat.',
    location: 'United States - Florida',
    contactPerson: 'Aaron Culver',
    phone: '+1-404-9037207',
    email: '—'
  },
  {
    type: 'Supplier',
    name: 'Capital Merchants Inc',
    products: 'HIBISCUS FLOWERS, HIBISCUS PETALS, SESAME SEEDS, MORINGA POWDER, soybeans, cassava flakes (gari)',
    established: 2013,
    employees: '11-50',
    desc: 'Supplier of HIBISCUS FLOWERS, HIBISCUS PETALS, SESAME SEEDS, MORINGA POWDER, soybeans, cassava flakes (gari).',
    location: 'United States - Pennsylvania',
    contactPerson: 'IBRAHEEM',
    phone: '+1-215-9439333',
    email: '—'
  },
  {
    type: 'Supplier',
    name: 'Grand Liberty Group Corp',
    products: 'Cooking Oil, Grains, Meat, Sugar, sunflower oil, corn oil, olive oil, soybean oil, rape-seed oil, wheat',
    established: 2015,
    employees: '11-50',
    desc: 'Supplier of Cooking Oil, Grains, Meat, Sugar, sunflower oil, corn oil, olive oil, soybean oil, rape-seed oil, wheat.',
    location: 'United States - New York',
    contactPerson: 'Mohamed Abdelghany',
    phone: '+1-337-3477054',
    email: '—'
  }
];

// Let's use git checkout or clean up src/data/mockData.ts
