- name: 🚀 Sync Files via FTP to BigRock
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ env.CLEAN_FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ./
          local-dir: ./dist/
          protocol: ftp
          port: 21
          dangerous-clean-slate: false
          security: loose
